# -*- coding: utf-8 -*-
"""Data_Cleaned_Coffee_Quality.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UL6q8P9zN2mZOitx0ILAT3TCETgl7H-W
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/Coffee_Qlty.csv')

def dfinfo(df):
  datainf = {
      'dtp': df.dtypes,
      'cnt':df.count(),
      'unq': df.nunique(),
      'nul': df.isna().sum(),
      'dup': df.duplicated().sum()
      }
  res = pd.DataFrame(datainf)
  return res

dfinfo(df)

df2 = df.dropna(subset = ['Continent.of.Origin'])

df2['Harvest.Year'].unique()

hymed = df2['Harvest.Year'].median()

df2['Harvest.Year'] = df2['Harvest.Year'].fillna(hymed)
df2['Harvest.Year'] = df2['Harvest.Year'].astype(int)

df2['Variety'].fillna('Not Known', inplace  = True)
df2['Color'].fillna('Not Known', inplace  = True)
df2['Processing.Method'].fillna('Not Known', inplace  = True)

df3 = df2.rename(columns = {
    'REC_ID':'Record Id',
'Species':'Species',
'Continent.of.Origin':'Continent Of Origin',
'Country.of.Origin':'Country Of Origin',
'Harvest.Year':'Harvest Year',
'Expiration':'Expiration',
'Variety':'Variety',
'Color':'Color',
'Processing.Method':'Processing Method',
'Aroma':'Aroma',
'Flavor':'Flavor',
'Aftertaste':'Aftertaste',
'Acidity':'Acidity',
'Body':'Body',
'Balance':'Balance',
'Uniformity':'Uniformity',
'Clean.Cup':'Clean Cup',
'Sweetness':'Sweetness',
'Moisture':'Moisture',
'Quakers':'Quakers',
'Category.One.Defects':'Category One Defects',
'Category.Two.Defects':'Category Two Defects',
})

dfinfo(df3)

# df3.to_csv('Coffee_Qlty_Clean.csv', index = False)