# -*- coding: utf-8 -*-
"""Data_Cleaned_Titanic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18KIEoK0lghYx9olMPt5WD2d5_hDQ4DZw
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df1 = pd.read_csv('/content/The Titanic dataset.csv')
df2 = pd.read_csv('/content/Titanic Dataset.csv')

def dfinfo(df):
  datainf = {
      'dtp': df.dtypes,
      'cnt':df.count(),
      'unq': df.nunique(),
      'nul': df.isna().sum(),
      'dup': df.duplicated().sum()
      }
  res = pd.DataFrame(datainf)
  return res

df1

header= df1.iloc[0]
df1 = df1.iloc[1:]
df1.columns = header

df1.columns = df1.columns.fillna('name')

dfinfo(df1)

df1.drop_duplicates(inplace = True)

dfmrg = pd.merge(left = df1, right = df2, how = 'left', left_on = 'name', right_on = 'name')

dfinfo(dfmrg)

dfmrg.drop(columns = ['pclass_y', 'survived_y', 'age_y', 'fare_x', 'embarked_y', 'sex'], inplace = True)

dfmrg['gender'].unique()

np.where(dfmrg['gender'].isna())

dfmrg.drop(2, inplace = True)

dfmrg['age_x'].unique()

dfmrg["age_x"] = dfmrg["age_x"].replace(["?"], None)
dfmrg['age_x'] = dfmrg['age_x'].astype(float)
meanage = dfmrg['age_x'].mean()
dfmrg['age_x'] = dfmrg['age_x'].fillna(meanage)

dfmrg['family'].nunique()

modefamily = dfmrg['family'].mode()[0]
modefamily

dfmrg['family'] = dfmrg['family'].fillna(modefamily)

dfinfo(dfmrg)

dfmrg['embarked_x'].unique()

modeembarked_x = dfmrg['embarked_x'].mode()[0]
dfmrg['embarked_x'] = dfmrg['embarked_x'].fillna(modeembarked_x)

dfmrg['sibsp'].unique()

dfmrg['sibsp'] = dfmrg['sibsp'].astype(float)
modesibsp = dfmrg['sibsp'].mode()[0]
#Using mode instead of mean as only 3 null values

dfmrg['sibsp'] = dfmrg['sibsp'].fillna(modesibsp)

dfmrg['parch'].unique()

modeparch = dfmrg['parch'].mode()[0]
#Using mode instead of mean as only 3 null values
dfmrg['parch'] = dfmrg['parch'].astype(float)
dfmrg['parch'] = dfmrg['parch'].fillna(modesibsp)

dfmrg['ticket'] = dfmrg['ticket'].fillna('Not_Known')
dfmrg['cabin'] = dfmrg['cabin'].fillna("Not_Known")

modefare_y = dfmrg['fare_y'].mode()[0]
dfmrg['fare_y'] = dfmrg['fare_y'].fillna(modefare_y)

dfmrg['boat'].unique()

dfmrg['boat'] = dfmrg['boat'].fillna("Not_Known")

dfmrg['body'] = dfmrg['body'].fillna(0)

dfmrg['home.dest'] = dfmrg['home.dest'].fillna("Not_Known")

dfmrg['family'] = dfmrg['family'].astype(int)
dfmrg['age_x'] = dfmrg['age_x'].astype(int)
dfmrg['date'] = pd.to_datetime(dfmrg['date'])
dfmrg['sibsp'] = dfmrg['sibsp'].astype(int)
dfmrg['parch'] = dfmrg['parch'].astype(int)
dfmrg['body'] = dfmrg['body'].astype(int)

dfmrg2 = dfmrg.rename(columns =
 {'sn': 'Serial Number',
  'pclass_x': 'Passenger Class',
  'survived_x': 'Survived',
  'name': 'Name',
  'gender': 'Gender',
  'age_x': 'Age',
  'family': 'Family',
  'embarked_x': 'Embarked Port',
  'date': 'Date',
  'sibsp': 'Siblings Or Spouces',
  'parch': 'Parent Or Children',
  'ticket': 'Ticket Number',
  'fare_y': 'Fare',
  'cabin': 'Cabin Number',
  'boat': 'Lifeboat Number',
  'body': 'Body Number',
  'home.dest': 'Home Destination'})

dfinfo(dfmrg2)

