# -*- coding: utf-8 -*-
"""EDA_Fifa23.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MRUNQ801aO1z4oSoacK64Qk9pRlEloJB
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("/content/CLEAN_FIFA23_official_data.csv")

df['Work Rate'].head(5)

df.info()

df2 =df.select_dtypes(include = ['int64'])

df2.drop(columns =["ID"], inplace = True)

df2.head(5)

corl = df2.corr()
corl

plt.figure(figsize = (12,10))
sns.heatmap(corl, annot=True, cmap='coolwarm', vmin=0.0, square = True)
plt.show()

# Histogram of Player & Age
plt.figure(figsize=(10, 6))
plt.hist(df['Age'], bins=30, color='skyblue', edgecolor='black')
plt.title('Distribution of Player Age')
plt.xlabel('Age')
plt.ylabel('Number of Players')
plt.show()

# Box Plot of Player Overall Ratings by Position
plt.figure(figsize=(14, 8))
sns.boxplot(x='Position', y='Overall', data=df)
plt.title('Box Plot of Player Overall Ratings by Position')
plt.xlabel('Position')
plt.ylabel('Overall Rating')
plt.show()

# Bar Plot of Average Overall Rating by Club
avgr= df.groupby('Club')['Overall'].mean().sort_values(ascending=False).head(8)
plt.figure(figsize=(14, 8))
avgr.plot(kind='bar', color='skyblue', edgecolor = 'black')
plt.title('Top 8 Clubs by Average Overall Rating')
plt.xlabel('Club')
plt.ylabel('Average Overall Rating')
plt.xticks(rotation=45)
plt.show()

# Bar Plot of Player Nationalities
top_nationalities = df['Nationality'].value_counts().head(8)
plt.figure(figsize=(14, 8))
top_nationalities.plot(kind='bar', color='skyblue', edgecolor = 'black')
plt.title('Top 8 Player Count by Nationalities')
plt.xlabel('Nationality')
plt.ylabel('Number of Players')
plt.xticks(rotation=45)
plt.show()

# Pie Chart of Player Preferred Foot
preferred_foot_counts = df['Preferred Foot'].value_counts()
plt.figure(figsize=(4, 4))
plt.pie(preferred_foot_counts, labels=preferred_foot_counts.index, autopct='%1.1f%%' ,
        colors=['skyblue', 'lightcoral'])
plt.title('Distribution of Player Preferred Foot')
plt.show()

# Bar Plot of Player Work Rates
plt.figure(figsize=(10, 6))
sns.countplot(x='Work Rate', data= df, order= df['Work Rate'].value_counts().index, palette='viridis')
plt.title('Distribution of Player Work Rates')
plt.xlabel('Work Rate')
plt.ylabel('Number of Players')
plt.xticks(rotation=45)
plt.show()

# Distribution of Player Ratings
plt.figure(figsize=(10, 6))
sns.histplot(df['Overall'], kde=True, color='skyblue', bins=20)
plt.title('Distribution of Player Ratings')
plt.xlabel('Overall Rating')
plt.ylabel('Frequency')
plt.show()