# -*- coding: utf-8 -*-
"""Web_Scrapping_News.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_22EcyoBeDOcwfKRhxz6GYA2MQ6J9OoQ
"""

import requests as res
from bs4 import BeautifulSoup as bs
import pandas as pd

# https://www.maharashtrasamachar.com/national/?page=1
# national
# business
# world
# sports
# entertainment
# lifestyle

def exturl(url):
    response = res.get(url)
    if response.status_code != 200:
        return None
    soup = bs(response.content, 'html.parser')

    National = soup.find_all("p", class_ = "title large mb-2")
    Related = soup.find_all("p", class_ = "title small")
    Date = soup.find_all("p", class_ = "date-wrapper medium")

    National_News = []
    Related_News = []
    News_Date = []

    for headline in National:
        National_News.append(headline.text)

    for headline in Related:
        Related_News.append(headline.text)

    for date in Date:
        News_Date.append(date.text)

    if len(National_News) == 1:
        National_News.extend([''] * (len(Related_News) - 1))

    if len(News_Date) == 1:
        News_Date = [News_Date[0]] * len(Related_News)

    df = pd.DataFrame({"National_News": National_News[:len(Related_News)], "Related_News": Related_News, "News_Date": News_Date[:len(Related_News)]})

    df.to_csv('News.csv', index=False)

    return {"National_News": National_News[:len(Related_News)], "Related_News": Related_News, "News_Date": News_Date[:len(Related_News)]}

Curr_Date = 'https://www.maharashtrasamachar.com/national/?page=1'

exturl(Curr_Date)

# https://www.maharashtrasamachar.com/national/?page=1
# national
# business
# world
# sports
# entertainment
# lifestyle