# -*- coding: utf-8 -*-
"""WebScrapping_E-Commerce.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1idmT1N2vEUfqKP6QQpfqMxVKgjd8M5UN
"""

import requests as res
from bs4 import BeautifulSoup as bs
import pandas as pd

url = 'https://webscraper.io/test-sites/e-commerce/allinone/phones/touch'

r = res.get(url)
r

soup = bs(r.text, "lxml")

# boxes = soup.find_all("div", class_ = "col-md-4 col-xl-4 col-lg-4")

# len(boxes)

XProduct = soup.find_all("a", class_ = "title" )
Product = []

for i in XProduct:
   Product.append(i.text)

XPrice = soup.find_all("h4", class_ = "price float-end card-title pull-right")
Price = []

for i in XPrice:
  Price.append(i.text)

XReview_Count = soup.find_all("p", class_="review-count float-end")
Review_Count = []

for i in XReview_Count:
  Review_Count.append(i.text)

df = pd.DataFrame({"Product": Product, "Price": Price, "Review_Count": Review_Count})

df

df.to_csv("Shopping.csv", index = False)